#!/usr/bin/env bash
pacman -S --needed base-devel git wget yajl wpa_supplicant dhclient
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

yay -S --noconfirm git base-devel neovim vim-plug fzf the_silver_searcher oh-my-zsh-git openvpn dnsmasq tmuxinator alacritty freerdp-git google-chrome ttf-meslo xseticon slack-desktop nodenv apache-tools light-git tmux openssh nodenv-node-build-git powertop tlp

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

powertop --auto-tune
systemctl enable --now tlp.service
systemctl enable --now tlp-sleep.service

# git
git config --global user.email "guidotarsia@gmail.com"
git config --global user.name "zzyyxxww"
git config --global core.editor nvim

echo "now run scripts/ symlinks plug and oh-my-zsh"
