#!/usr/bin/env bash
pacman -S --needed base-devel git wget yajl
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

yay -S --noconfirm git base-devel neovim vim-plug fzf the_silver_searcher oh-my-zsh-git openvpn dnsmasq tmuxinator alacritty discord franz-bin freerdp-git godot google-chrome ttf-meslo xseticon slack-desktop nodenv apache-tools light-git tmux openssh

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo "now run scripts/ symlinks plug and oh-my-zsh"
