#!/usr/bin/env bash
sudo pacman -S --needed base-devel git wget yajl
git clone https://aur.archlinux.org/package-query.git
cd package-query/
makepkg -si
cd ..
git clone https://aur.archlinux.org/yaourt.git
cd yaourt/
makepkg -si
cd ..
sudo rm -dR yaourt/ package-query/

yaourt -S --noconfirm neovim autokey-py3 vim-plug the_silver_searcher oh-my-zsh-git
