#!/usr/bin/env bash
ln -s ./.alacritty.yml $HOME/.alacritty.yml
ln -s ./.zshrc $HOME/.zshrc
ln -s ./.vimrc $HOME/.vimrc
ln -s ./.tmux.conf $HOME/.tmux.conf
ln -s ./.i3.conf $HOME/.i3/config
ln -s ./.rofi.conf $HOME/.config/rofi/config
touch $HOME/.zshenv
