#!/usr/bin/env bash
ln -s $HOME/git/dotfiles/.alacritty.yml $HOME/.alacritty.yml
ln -s $HOME/git/dotfiles/.zshrc $HOME/.zshrc
ln -s $HOME/git/dotfiles/.vimrc $HOME/.vimrc
ln -s $HOME/git/dotfiles/.vimrc $HOME/.config/nvim/init.vim
ln -s $HOME/git/dotfiles/.tmux.conf $HOME/.tmux.conf
# ln -s ./.i3.conf $HOME/.i3/config
# ln -s ./.rofi.conf $HOME/.config/rofi/config
touch $HOME/.zshenv
