#!/usr/bin/bash

# zsh
echo linking .zshrc...
sudo ln -sf $FILES/zsh/.zshrc /root/.zshrc
sudo touch /root/.zshenv

# vim
echo linking .zshrc...
sudo mkdir -p /root/.config/nvim
sudo ln -sf $FILES/vim/.vimrc /root/.config/nvim/init.vim

# console
echo linking br-nitro5.map.gz...
sudo ln -sf $FILES/console/br-nitro5.map.gz /usr/share/kbd/keymaps/i386/qwerty/br-nitro5.map.gz
echo linking /etc/vconsole.conf...
sudo ln -sf $FILES/console/vconsole.conf /etc/vconsole.conf
