#!/usr/bin/env bash

# essentials
bash ./user-bin/from-mother
bash ./user-bin/git
bash ./user-bin/power
bash ./user-bin/powerline
bash ./user-bin/tmux
bash ./user-bin/vim
bash ./user-bin/zsh

bash ./user-bin/symlinks
