#!/usr/bin/env bash

echo linking br-nitro5.map.gz...
ln -sf $FILES/console/br-nitro5.map.gz /usr/share/kbd/keymaps/i386/qwerty/br-nitro5.map.gz
echo linking /etc/vconsole.conf...
ln -sf $FILES/console/vconsole.conf /etc/vconsole.conf

echo configuring console...
setfont latarcyrheb-sun32
loadkeys br-nitro5
