#!/usr/bin/env bash

DEFAULT_PASSPHRASE=/.wifi
PASSPHRASE=/.kyokai-wifi
killall wpa_supplicant
echo connecting wifi...
OUTPUT=/tmp/wifi_output.txt
rm -f $OUTPUT
echo $PASSPHRASE
wpa_supplicant -B -c $PASSPHRASE -i wlp2s0 -f $OUTPUT
echo waiting on wpa_supplicant CTRL-EVENT-CONNECTED...
tail -f $OUTPUT | grep -q "CTRL-EVENT-CONNECTED"
dhclient
ping -c 1 -q google.com
