#!/usr/bin/bash
set -x
ln -s $HOME/git/dotfiles/.alacritty.yml $HOME/.alacritty.yml
ln -s $HOME/git/dotfiles/.zshrc $HOME/.zshrc
ln -s $HOME/git/dotfiles/.vimrc $HOME/.vimrc
ln -s $HOME/git/dotfiles/.tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.config/nvim/init.vim
ln -s $HOME/git/dotfiles/.vimrc $HOME/.config/nvim/init.vim

touch $HOME/.zshenv

# root user
sudo mkdir -p /root/.config/nvim
sudo ln -s $HOME/git/dotfiles/.zshrc /root/.zshrc
sudo ln -s $HOME/git/dotfiles/.vimrc /root/.config/nvim/init.vim
sudo ln -s $HOME/git/dotfiles/br-nitro5.map.gz /usr/share/kbd/keymaps/i386/qwerty/br-nitro5.map.gz

# ln -s ./.i3.conf $HOME/.i3/config
# ln -s ./.rofi.conf $HOME/.config/rofi/config
