#!/usr/bin/bash
set -x
ln -sf $HOME/dotfiles/.alacritty.yml $HOME/.alacritty.yml
ln -sf $HOME/dotfiles/.zshrc $HOME/.zshrc
ln -sf $HOME/dotfiles/.vimrc $HOME/.vimrc
ln -sf $HOME/dotfiles/.tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.config/autostart
ln -sf $HOME/dotfiles/autostart/boot.desktop $HOME/.config/autostart/boot.desktop
ln -sf $HOME/dotfiles/autostart/boot.zsh $HOME/.config/autostart/boot.zsh

mkdir -p $HOME/.config/nvim
ln -sf $HOME/dotfiles/.vimrc $HOME/.config/nvim/init.vim

touch $HOME/.zshenv

# root user
sudo mkdir -p /root/.config/nvim
sudo ln -sf $HOME/dotfiles/.zshrc /root/.zshrc
sudo ln -sf $HOME/dotfiles/.vimrc /root/.config/nvim/init.vim
sudo ln -sf $HOME/dotfiles/br-nitro5.map.gz /usr/share/kbd/keymaps/i386/qwerty/br-nitro5.map.gz

# ln -sf ./.i3.conf $HOME/.i3/config
# ln -sf ./.rofi.conf $HOME/.config/rofi/config
