#!/usr/bin/env bash

echo installing user extra packages...
yay -S --noconfirm freerdp-git slack-desktop discord franz-bin godot apache-tools obs-studio jq alsa-utils libreoffice rdesktop freerdp-git
