#!/usr/bin/env bash

echo copying user things from mother...
cp -R /mother/home/romigui/.ssh $HOME/
cp -R /mother/home/romigui/vpn $HOME/
cp /mother/home/romigui/.zsh_history $HOME/
cp /git-owner/home/romigui/.zshenv $HOME/
ln -sf /git-owner/home/romigui/git $HOME/git
