#!/usr/bin/env bash

FILES=$(readlink -f $(dirname $0)/../files)

# ln -sf $FILES/.Xresources $HOME/.Xresources

# alacritty
echo linking .alacritty.yml...
ln -sf $FILES/alacritty/.alacritty.yml $HOME/.alacritty.yml

# zsh
echo linking .zshrc...
ln -sf $FILES/zsh/.zshrc $HOME/.zshrc
touch $HOME/.zshenv

# vim
mkdir -p $HOME/.config/nvim
echo linking .vimrc...
ln -sf $FILES/vim/.vimrc $HOME/.config/nvim/init.vim
ln -sf $FILES/vim/.vimrc $HOME/.vimrc
mkdir -p $FILES/vim/templates
ln -sf $FILES/vim/templates/* $HOME/.vim/templates/

# tmux
echo linking .tmux.conf...
ln -sf $FILES/tmux/.tmux.conf $HOME/.tmux.conf
mkdir -p $HOME/.tmux
echo linking .tmux/resurrect...
ln -sf $FILES/tmux-resurrect $HOME/.tmux/resurrect
echo linking .config/tmuxinator...
ln -sf $FILES/tmuxinator $HOME/.config/tmuxinator

# fonts
echo linking fonts.conf...
mkdir -p $HOME/.config/
ln -sf $FILES/fontconfig $HOME/.config/fontconfig

# autostart
echo copying .config/autostart/boot...
# mkdir -p $HOME/.config/autostart
ln -sf $FILES/autostart/boot.desktop $HOME/.config/autostart/boot.desktop
ln -sf $FILES/autostart/boot.zsh $HOME/.config/autostart/boot.zsh

echo linking openbox...
ln -sf $FILES/openbox/ $HOME/.config/openbox

echo linking tint2...
ln -sf $FILES/tint2/ $HOME/.config/tint2

echo linking mpv...
mkdir -p $HOME/.config/mpv
ln -sf $FILES/mpv/input.conf $HOME/.config/mpv/input.conf

echo symlinks complete!
