#!/usr/bin/env bash

# time
FILES=$(readlink -f $(dirname $0)/files)

echo "setting up time and /etc files"
ln -sf /usr/share/zoneinfo/Brazil/West /etc/localtime
hwclock --systohc

ln -sf $FILES/locale.gen /etc/locale.gen
ln -sf $FILES/locale.conf /etc/locale.conf
ln -sf $FILES/vconsole.conf /etc/vconsole.conf
ln -sf $FILES/hostname /etc/hostname
locale-gen

pacman -S intel-ucode efibootmgr grub openbox python2-xdg zsh sudo wpa_supplicant dhclient

echo "requesting password for root..."
passwd
useradd -m -s /bin/zsh romigui
echo "requesting password for romigui..."
passwd romigui
mv /home/dotfiles/ /home/romigui/dotfiles
cd /home/romigui/dotfiles && chown -R romigui:romigui .

echo "adding romigui to sudoers..."
echo "romigui ALL=(ALL) ALL" > /etc/sudoers

echo "configuring grub..."
mkdir -p /esp
mount /dev/sda1 /esp
grub-install --target=x86_64-efi --efi-directory=/esp --bootloader-id="Awesome arch"
grub-mkconfig -o /boot/grub/grub.cfg
